### PR TITLE
Add support for adding to .bash_profile on Mac OS

### PR DESCRIPTION
**Pull request by muya**
Check if user is using `.bash_profile`, then add commands to it

### CODE REVIEW

**Comment by ankitvad** [comment]
First of all, i'd like to thank you for taking out the time to modify it for MacOS. I don't have one, so that makes testing a problem.
Secondly, lot's of Mac systems have .bashrc files and a lot of linux systems have .bash_profile. Depends on the shell you're using.
 Hence, i can merge this in the main repo. but it would'nt make much difference and might miss the original thing on linux systems. 

I think a better way would be to add this part to 2 files. .bashrc and .bash_profile. And, then you're terminal/shell can pick up whichever one it uses.

Did i miss anything ?

**Comment by ankitvad** [comment]
http://www.joshstaiger.org/archives/2005/07/bash_profile_vs.html

Please try running this directly, via .bashrc and see if you're shell can pick this up. As, both of the files can be used.

->Added 2 files and closed.
Thanks.

**Comment by ankitvad** [comment]
Modified it to:<pre><code>#For people using .bashrc.
if [ -f "$BASH_FILE" ]; then
    echo 'export PATH=$PATH:~/.local/bin/' >> "$BASH_FILE"
    echo 'alias goto=". goto"' >> "$BASH_FILE"
    echo -e "Added Stuff in .bashrc"
        .  ~/.bashrc
fi
#Creating new bash_profile file, if doesnt exist. if exists, the appending
#value. Some people on MAC don't use .bashrc.
if [ -f "$BASH_FILE2" ]; then
    echo 'export PATH=$PATH:~/.local/bin/' >> "$BASH_FILE2"
    echo 'alias goto=". goto"' >> "$BASH_FILE2"
    echo -e "Added Stuff in .bash_profile"
        .  ~/.bash_profile
fi
</pre></code>
Because some People have both. Like me.!!

**Comment by muya** [comment]
Yes, I agree. Adding it to both files is a more foolproof solution.

**Pull request closed without merging**
